#!/bin/sh
# PROVIDE: mvtserver
# REQUIRE: DAEMON NETWORKING
# KEYWORD: shutdown

. /etc/rc.subr

name="mvtserver"
rcvar="mvtserver_enable"

command="/usr/sbin/daemon"
procname="/usr/local/bin/mvt-server"
pidfile="/var/run/mvtserver.pid"

config_dir="/usr/local/etc/mvt-server"
config_file="${config_dir}/config.yaml"
cache_dir="/var/cache/mvt-server"
assets_dir="${config_dir}/assets"

# Export variables from .env to the environment
if [ -f "${config_dir}/.env" ]; then
    export $(grep -v '^#' "${config_dir}/.env" | xargs)
fi

load_rc_config $name

: ${mvtserver_enable:="NO"}
: ${mvtserver_flags:=""}

# Build arguments with daemon
command_args="-f -p ${pidfile} /usr/local/bin/mvt-server --config ${config_file} ${mvtserver_flags} >> /var/log/mvt-server.log 2>&1"

required_dirs="${config_dir} ${cache_dir} ${assets_dir}"

run_rc_command "$1"
